swagger: '2.0'
host: demo1-221313.appspot.com
info:
  version: v1
  title: My API
paths:
  /view/Angular/Index:
    get:
      tags:
        - Angular
      operationId: ViewAngularIndexGet
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
  /api/Container:
    get:
      tags:
        - Container
      operationId: ApiContainerGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  '/api/Container/{id}':
    get:
      tags:
        - Container
      operationId: ApiContainerByIdGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
    put:
      tags:
        - Container
      operationId: ApiContainerByIdPut
      consumes:
        - application/json-patch+json
        - application/json
        - text/json
        - application/*+json
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
        - name: value
          in: body
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Container
      operationId: ApiContainerByIdDelete
      consumes: []
      produces: []
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
  /api/ContainerFire/PostToYardBase:
    post:
      tags:
        - ContainerFire
      operationId: ApiContainerFirePostToYardBasePost
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: containerno
          in: query
          required: false
          type: string
        - name: source
          in: query
          required: false
          type: string
        - name: base64image
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/Sheet:
    get:
      tags:
        - Drive
      operationId: ApiSheetGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  '/api/Sheet/{id}':
    get:
      tags:
        - Drive
      operationId: ApiSheetByIdGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/Sheet/Create:
    get:
      tags:
        - Drive
      operationId: ApiSheetCreateGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/enbloc/PostToYardBase:
    post:
      tags:
        - Enbloc
      operationId: ApiEnblocPostToYardBasePost
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: containerno
          in: query
          required: false
          type: string
        - name: vesselno
          in: query
          required: false
          type: string
        - name: yardid
          in: query
          required: false
          type: string
        - name: base64image
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  '/api/enbloc/GetYardDetails/{containerno}/{userName}':
    get:
      tags:
        - Enbloc
      operationId: ApiEnblocGetYardDetailsByContainernoByUserNameGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: containerno
          in: path
          required: true
          type: string
        - name: userName
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  /view/Firestore/Index:
    get:
      tags:
        - Firestore
      operationId: ViewFirestoreIndexGet
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
  /view/Firestore/Yard:
    get:
      tags:
        - Firestore
      operationId: ViewFirestoreYardGet
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
  /view/Firestore/MSC:
    get:
      tags:
        - Firestore
      operationId: ViewFirestoreMSCGet
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
  /view/Firestore/ISGEC:
    get:
      tags:
        - Firestore
      operationId: ViewFirestoreISGECGet
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
  /view/Firestore/Enbloc:
    get:
      tags:
        - Firestore
      operationId: ViewFirestoreEnblocGet
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
  /view/Firestore/EnblocData:
    get:
      tags:
        - Firestore
      operationId: ViewFirestoreEnblocDataGet
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
  /mail/gmail/send:
    get:
      tags:
        - Gmail
      operationId: MailGmailSendGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  /home/index:
    get:
      tags:
        - Home
      operationId: HomeIndexGet
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
  /home/test:
    get:
      tags:
        - Home
      operationId: HomeTestGet
      consumes: []
      produces: []
      parameters: []
      responses:
        '200':
          description: Success
  /home/edit:
    get:
      tags:
        - Home
      operationId: HomeEditGet
      consumes: []
      produces: []
      parameters:
        - name: id
          in: query
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: Success
  /home/post:
    post:
      tags:
        - Home
      operationId: HomePostPost
      consumes: []
      produces: []
      parameters:
        - name: id
          in: query
          required: false
          type: integer
          format: int32
        - name: sbno
          in: query
          required: false
          type: string
        - name: containerno
          in: query
          required: false
          type: string
        - name: shippingline
          in: query
          required: false
          type: string
        - name: movementdate
          in: query
          required: false
          type: string
        - name: color
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Success
  /home/delete:
    get:
      tags:
        - Home
      operationId: HomeDeleteGet
      consumes: []
      produces: []
      parameters:
        - name: id
          in: query
          required: false
          type: integer
          format: int32
      responses:
        '200':
          description: Success
  /api/isgec/Create:
    get:
      tags:
        - IsgecFirebase
      operationId: ApiIsgecCreateGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  '/api/mscExcel/GetContainerDetails/{id}':
    get:
      tags:
        - Msc
      operationId: ApiMscExcelGetContainerDetailsByIdGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/mscExcel/Create:
    get:
      tags:
        - Msc
      operationId: ApiMscExcelCreateGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  '/api/msc/GetContainerDetails/{containerno}':
    get:
      tags:
        - MscFirebase
      operationId: ApiMscGetContainerDetailsByContainernoGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: containerno
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/msc/Create:
    get:
      tags:
        - MscFirebase
      operationId: ApiMscCreateGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/Drive:
    get:
      tags:
        - Sheet
      operationId: ApiDriveGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  '/api/Drive/{id}':
    get:
      tags:
        - Sheet
      operationId: ApiDriveByIdGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/Values:
    get:
      tags:
        - Values
      operationId: ApiValuesGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: container
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  '/api/Yard/GetYardDetails/{id}':
    get:
      tags:
        - Yard
      operationId: ApiYardGetYardDetailsByIdGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/yard/Create:
    get:
      tags:
        - Yard
      operationId: ApiYardCreateGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters: []
      responses:
        '200':
          description: Success
          schema:
            type: string
  /api/Yard/PostToYardBase:
    post:
      tags:
        - Yard
      operationId: ApiYardPostToYardBasePost
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: containerno
          in: query
          required: false
          type: string
        - name: yardid
          in: query
          required: false
          type: string
        - name: base64image
          in: query
          required: false
          type: string
        - name: timestamp
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
definitions: {}
