runtime: aspnetcore
env: flex
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10  
endpoints_api_service:
  name: elabs-215913.appspot.com
  rollout_strategy: managed
beta_settings:
    cloud_sql_instances: "elabs-215913:asia-south1:eslabs=tcp:5432"